version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      - run:
          name: Echo
          command: echo "This step isn't very useful"
      - run:
          name: pwd
          command: pwd
      - run:
          name: ls
          command: ls
