version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      - run:
          name: Install curl
          command: sudo apt-get install curl
          # command: curl https://get.please.build | bash
