version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest

    steps:
      - checkout

      - run:
          name: Check curl
          command: curl -h
          # command: curl https://get.please.build | bash
