package(default_visibility = ["PUBLIC"])

export_file (
  name = 'remote',
  src = 'remote.build_defs',
  visibility = ['PUBLIC']
)

export_file (
  name = 'rust',
  src = 'rust.build_defs',
  visibility = ['PUBLIC'],
)
